services:
  - type: web
    name: api-tree-service
    env: java
    plan: starter
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Xmx512m -Xms256m -jar target/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 3600000
      - key: JWT_REFRESH_EXPIRATION
        value: 86400000
      - key: JWT_ISSUER
        value: api-tree-service
      - key: CORS_ALLOWED_ORIGINS
        value: https://urag.mn,https://www.urag.mn
      - key: CORS_ALLOWED_METHODS
        value: GET,POST,PUT,DELETE,OPTIONS
      - key: CORS_ALLOWED_HEADERS
        value: Authorization,Content-Type,X-Requested-With,Accept,Origin
      - key: CORS_ALLOW_CREDENTIALS
        value: true
      - key: RATE_LIMIT_ENABLED
        value: true
      - key: RATE_LIMIT_REQUESTS
        value: 60
      - key: API_FILE_UPLOAD_DIR
        value: /tmp/uploads
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: davaatest@gmail.com
      - key: MAIL_PASSWORD
        value: jrlg ntvt qvnv klop
      - key: CLOUDINARY_CLOUD_NAME
        value: dyntquf1i
      - key: CLOUDINARY_API_KEY
        value: 748651478547981
      - key: CLOUDINARY_API_SECRET
        value: EdfGyKUvPcuc6Y0doG_MFhGvHFc

databases:
  - name: postgres
    plan: starter
