spring:
  application:
    name: api-tree-service
  datasource:
    url: jdbc:postgresql://51.20.251.210:5432/ms_family_tree
    username: daaduu
    password: KiDavaa08
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: family
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    defer-datasource-initialization: true
  jackson:
    default-property-inclusion: non-null
    deserialization:
      fail-on-unknown-properties: false
file:
  uploadDir: ${API_FILE_UPLOAD_DIR}
server:
  port: 8083
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: metrics, health
