spring:
  application:
    name: api-tree-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d2mi6p95pdvs738seek0-a:5432/ms_family_tree}
    # username: ${SPRING_DATASOURCE_USERNAME}
    # password: ${SPRING_DATASOURCE_PASSWORD}
    # url: jdbc:postgresql://localhost:5433/ms_family_tree
    username: ${SPRING_DATASOURCE_USERNAME:daaduu}
    password: ${SPRING_DATASOURCE_PASSWORD:nzWEASAlVBjjyVdJAonKcKStcvfACMYR}
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        default_schema: family
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    defer-datasource-initialization: true
  jackson:
    default-property-inclusion: non-null
    deserialization:
      fail-on-unknown-properties: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: davaatest@gmail.com
    password: jrlg ntvt qvnv klop
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
file:
  uploadDir: ${API_FILE_UPLOAD_DIR:./uploads}
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: metrics, health
