spring:
  application:
    name: api-tree-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        default_schema: family
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    defer-datasource-initialization: true
  jackson:
    default-property-inclusion: non-null
    deserialization:
      fail-on-unknown-properties: false
file:
  uploadDir: ${API_FILE_UPLOAD_DIR}
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: metrics, health
